### ISSUE TITLE
hey bro pls change your coursera link

### ISSUE THREAD

**Issue by kratos-respawned** [kartikShrivastava015/module-02-solution#1]
change your link , the link you provided is redirecting me to this repo instead of that webpage

**Comment by kartikShrivastava015** [comment]
Dude how I am supposed to host it? If I will share the webpage it will only
be available with html and styles won't work!

**Comment by kratos-respawned** [comment]
change your css file name to style2.css 
I tried changing this but was unable to push to it your github dunno why

**Comment by kartikShrivastava015** [comment]
Fine bro I'll do it but in case if you still find some issues there. Do me
a favor and plz just pass me with the minimum score. I need this
certificate for my semester credits. I am done with everything else on the
course, this is the only assignment stuck in between the completion of the
course. My classes has begun and prof is asking for it ASAP. Please think
about it for once.
